### ISSUE TITLE
Can you copy Sample-JET-CCA-Demo-Card into components

### ISSUE THREAD

**Issue by JohnRSim** [oracle/content-and-experience-toolkit#1]
The Sample-JET-CCA-Demo-Card is hidden within the JET starter template.
\data\templates\JETStarterTemplate.zip\components\Sample-JET-CCA-Demo-Card

Could you expose this within \data\components\ as well?

The only JET CCA component that can be found by searching is on Igors blog - which is out of date the sample one hidden in the starter template is clean and more usable.

Many Thanks

**Comment by steveaburns** [comment]
John, thank you for the request.  We can make Sample-JET-CCA-Demo-Card available from \data\components -- enabling `cec create-component new-comp -f Sample-JET-CCA-Demo-Card`.

The component IS currently within the JET Starter Template because the template (the page layout in the theme) sets up dependencies for JET.  As such, the Sample-JET-CCA-Demo-Card component will not run in other templates, unless they are setup for JET.

**Comment by steveaburns** [comment]
Added JET CCA component template.  Use with:

`cec create-component JET-CCA-Demo-Card`

https://github.com/oracle/content-and-experience-toolkit/releases/tag/19.2.1f
